<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CapEnjoyer.API</AssemblyName>
    <RootNamespace>CapEnjoyer.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CapEnjoyer.BL\CapEnjoyer.BL.csproj"/>
    <ProjectReference Include="..\CapEnjoyer.DAL\CapEnjoyer.DAL.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="CapEnjoyer.API\wwwroot\images\caps\"/>
    <Folder Include="wwwroot\images\caps\"/>
  </ItemGroup>

</Project>
