namespace DAL.Seeds;

using Entities;
using Microsoft.EntityFrameworkCore;

public static class CountrySeed
{
    public static List<Country> Seed(ModelBuilder modelBuilder)
    {
        var countries = new List<Country>
        {
            new() { Id = Guid.NewGuid(), Name = "Afghanistan" },
            new() { Id = Guid.NewGuid(), Name = "Albania" },
            new() { Id = Guid.NewGuid(), Name = "Algeria" },
            new() { Id = Guid.NewGuid(), Name = "Andorra" },
            new() { Id = Guid.NewGuid(), Name = "Angola" },
            new() { Id = Guid.NewGuid(), Name = "Antigua and Barbuda" },
            new() { Id = Guid.NewGuid(), Name = "Argentina" },
            new() { Id = Guid.NewGuid(), Name = "Armenia" },
            new() { Id = Guid.NewGuid(), Name = "Australia" },
            new() { Id = Guid.NewGuid(), Name = "Austria" },
            new() { Id = Guid.NewGuid(), Name = "Azerbaijan" },
            new() { Id = Guid.NewGuid(), Name = "The Bahamas" },
            new() { Id = Guid.NewGuid(), Name = "Bahrain" },
            new() { Id = Guid.NewGuid(), Name = "Bangladesh" },
            new() { Id = Guid.NewGuid(), Name = "Barbados" },
            new() { Id = Guid.NewGuid(), Name = "Belarus" },
            new() { Id = Guid.NewGuid(), Name = "Belgium" },
            new() { Id = Guid.NewGuid(), Name = "Belize" },
            new() { Id = Guid.NewGuid(), Name = "Benin" },
            new() { Id = Guid.NewGuid(), Name = "Bhutan" },
            new() { Id = Guid.NewGuid(), Name = "Bolivia" },
            new() { Id = Guid.NewGuid(), Name = "Bosnia and Herzegovina" },
            new() { Id = Guid.NewGuid(), Name = "Botswana" },
            new() { Id = Guid.NewGuid(), Name = "Brazil" },
            new() { Id = Guid.NewGuid(), Name = "Brunei" },
            new() { Id = Guid.NewGuid(), Name = "Bulgaria" },
            new() { Id = Guid.NewGuid(), Name = "Burkina Faso" },
            new() { Id = Guid.NewGuid(), Name = "Burundi" },
            new() { Id = Guid.NewGuid(), Name = "Cabo Verde" },
            new() { Id = Guid.NewGuid(), Name = "Cambodia" },
            new() { Id = Guid.NewGuid(), Name = "Cameroon" },
            new() { Id = Guid.NewGuid(), Name = "Canada" },
            new() { Id = Guid.NewGuid(), Name = "Central African Republic" },
            new() { Id = Guid.NewGuid(), Name = "Chad" },
            new() { Id = Guid.NewGuid(), Name = "Chile" },
            new() { Id = Guid.NewGuid(), Name = "China" },
            new() { Id = Guid.NewGuid(), Name = "Colombia" },
            new() { Id = Guid.NewGuid(), Name = "Comoros" },
            new() { Id = Guid.NewGuid(), Name = "Congo, Democratic Republic of the" },
            new() { Id = Guid.NewGuid(), Name = "Congo, Republic of the" },
            new() { Id = Guid.NewGuid(), Name = "Costa Rica" },
            new() { Id = Guid.NewGuid(), Name = "Côte d’Ivoire" },
            new() { Id = Guid.NewGuid(), Name = "Croatia" },
            new() { Id = Guid.NewGuid(), Name = "Cuba" },
            new() { Id = Guid.NewGuid(), Name = "Cyprus" },
            new() { Id = Guid.NewGuid(), Name = "Czech Republic" },
            new() { Id = Guid.NewGuid(), Name = "Denmark" },
            new() { Id = Guid.NewGuid(), Name = "Djibouti" },
            new() { Id = Guid.NewGuid(), Name = "Dominica" },
            new() { Id = Guid.NewGuid(), Name = "Dominican Republic" },
            new() { Id = Guid.NewGuid(), Name = "East Timor (Timor-Leste)" },
            new() { Id = Guid.NewGuid(), Name = "Ecuador" },
            new() { Id = Guid.NewGuid(), Name = "Egypt" },
            new() { Id = Guid.NewGuid(), Name = "El Salvador" },
            new() { Id = Guid.NewGuid(), Name = "Equatorial Guinea" },
            new() { Id = Guid.NewGuid(), Name = "Eritrea" },
            new() { Id = Guid.NewGuid(), Name = "Estonia" },
            new() { Id = Guid.NewGuid(), Name = "Eswatini" },
            new() { Id = Guid.NewGuid(), Name = "Ethiopia" },
            new() { Id = Guid.NewGuid(), Name = "Fiji" },
            new() { Id = Guid.NewGuid(), Name = "Finland" },
            new() { Id = Guid.NewGuid(), Name = "France" },
            new() { Id = Guid.NewGuid(), Name = "Gabon" },
            new() { Id = Guid.NewGuid(), Name = "The Gambia" },
            new() { Id = Guid.NewGuid(), Name = "Georgia" },
            new() { Id = Guid.NewGuid(), Name = "Germany" },
            new() { Id = Guid.NewGuid(), Name = "Ghana" },
            new() { Id = Guid.NewGuid(), Name = "Greece" },
            new() { Id = Guid.NewGuid(), Name = "Grenada" },
            new() { Id = Guid.NewGuid(), Name = "Guatemala" },
            new() { Id = Guid.NewGuid(), Name = "Guinea" },
            new() { Id = Guid.NewGuid(), Name = "Guinea-Bissau" },
            new() { Id = Guid.NewGuid(), Name = "Guyana" },
            new() { Id = Guid.NewGuid(), Name = "Haiti" },
            new() { Id = Guid.NewGuid(), Name = "Honduras" },
            new() { Id = Guid.NewGuid(), Name = "Hungary" },
            new() { Id = Guid.NewGuid(), Name = "Iceland" },
            new() { Id = Guid.NewGuid(), Name = "India" },
            new() { Id = Guid.NewGuid(), Name = "Indonesia" },
            new() { Id = Guid.NewGuid(), Name = "Iran" },
            new() { Id = Guid.NewGuid(), Name = "Iraq" },
            new() { Id = Guid.NewGuid(), Name = "Ireland" },
            new() { Id = Guid.NewGuid(), Name = "Israel" },
            new() { Id = Guid.NewGuid(), Name = "Italy" },
            new() { Id = Guid.NewGuid(), Name = "Jamaica" },
            new() { Id = Guid.NewGuid(), Name = "Japan" },
            new() { Id = Guid.NewGuid(), Name = "Jordan" },
            new() { Id = Guid.NewGuid(), Name = "Kazakhstan" },
            new() { Id = Guid.NewGuid(), Name = "Kenya" },
            new() { Id = Guid.NewGuid(), Name = "Kiribati" },
            new() { Id = Guid.NewGuid(), Name = "Korea, North" },
            new() { Id = Guid.NewGuid(), Name = "Korea, South" },
            new() { Id = Guid.NewGuid(), Name = "Kosovo" },
            new() { Id = Guid.NewGuid(), Name = "Kuwait" },
            new() { Id = Guid.NewGuid(), Name = "Kyrgyzstan" },
            new() { Id = Guid.NewGuid(), Name = "Laos" },
            new() { Id = Guid.NewGuid(), Name = "Latvia" },
            new() { Id = Guid.NewGuid(), Name = "Lebanon" },
            new() { Id = Guid.NewGuid(), Name = "Lesotho" },
            new() { Id = Guid.NewGuid(), Name = "Liberia" },
            new() { Id = Guid.NewGuid(), Name = "Libya" },
            new() { Id = Guid.NewGuid(), Name = "Liechtenstein" },
            new() { Id = Guid.NewGuid(), Name = "Lithuania" },
            new() { Id = Guid.NewGuid(), Name = "Luxembourg" },
            new() { Id = Guid.NewGuid(), Name = "Madagascar" },
            new() { Id = Guid.NewGuid(), Name = "Malawi" },
            new() { Id = Guid.NewGuid(), Name = "Malaysia" },
            new() { Id = Guid.NewGuid(), Name = "Maldives" },
            new() { Id = Guid.NewGuid(), Name = "Mali" },
            new() { Id = Guid.NewGuid(), Name = "Malta" },
            new() { Id = Guid.NewGuid(), Name = "Marshall Islands" },
            new() { Id = Guid.NewGuid(), Name = "Mauritania" },
            new() { Id = Guid.NewGuid(), Name = "Mauritius" },
            new() { Id = Guid.NewGuid(), Name = "Mexico" },
            new() { Id = Guid.NewGuid(), Name = "Micronesia, Federated States of" },
            new() { Id = Guid.NewGuid(), Name = "Moldova" },
            new() { Id = Guid.NewGuid(), Name = "Monaco" },
            new() { Id = Guid.NewGuid(), Name = "Mongolia" },
            new() { Id = Guid.NewGuid(), Name = "Montenegro" },
            new() { Id = Guid.NewGuid(), Name = "Morocco" },
            new() { Id = Guid.NewGuid(), Name = "Mozambique" },
            new() { Id = Guid.NewGuid(), Name = "Myanmar (Burma)" },
            new() { Id = Guid.NewGuid(), Name = "Namibia" },
            new() { Id = Guid.NewGuid(), Name = "Nauru" },
            new() { Id = Guid.NewGuid(), Name = "Nepal" },
            new() { Id = Guid.NewGuid(), Name = "Netherlands" },
            new() { Id = Guid.NewGuid(), Name = "New Zealand" },
            new() { Id = Guid.NewGuid(), Name = "Nicaragua" },
            new() { Id = Guid.NewGuid(), Name = "Niger" },
            new() { Id = Guid.NewGuid(), Name = "Nigeria" },
            new() { Id = Guid.NewGuid(), Name = "North Macedonia" },
            new() { Id = Guid.NewGuid(), Name = "Norway" },
            new() { Id = Guid.NewGuid(), Name = "Oman" },
            new() { Id = Guid.NewGuid(), Name = "Pakistan" },
            new() { Id = Guid.NewGuid(), Name = "Palau" },
            new() { Id = Guid.NewGuid(), Name = "Panama" },
            new() { Id = Guid.NewGuid(), Name = "Papua New Guinea" },
            new() { Id = Guid.NewGuid(), Name = "Paraguay" },
            new() { Id = Guid.NewGuid(), Name = "Peru" },
            new() { Id = Guid.NewGuid(), Name = "Philippines" },
            new() { Id = Guid.NewGuid(), Name = "Poland" },
            new() { Id = Guid.NewGuid(), Name = "Portugal" },
            new() { Id = Guid.NewGuid(), Name = "Qatar" },
            new() { Id = Guid.NewGuid(), Name = "Romania" },
            new() { Id = Guid.NewGuid(), Name = "Russia" },
            new() { Id = Guid.NewGuid(), Name = "Rwanda" },
            new() { Id = Guid.NewGuid(), Name = "Saint Kitts and Nevis" },
            new() { Id = Guid.NewGuid(), Name = "Saint Lucia" },
            new() { Id = Guid.NewGuid(), Name = "Saint Vincent and the Grenadines" },
            new() { Id = Guid.NewGuid(), Name = "Samoa" },
            new() { Id = Guid.NewGuid(), Name = "San Marino" },
            new() { Id = Guid.NewGuid(), Name = "Sao Tome and Principe" },
            new() { Id = Guid.NewGuid(), Name = "Saudi Arabia" },
            new() { Id = Guid.NewGuid(), Name = "Senegal" },
            new() { Id = Guid.NewGuid(), Name = "Serbia" },
            new() { Id = Guid.NewGuid(), Name = "Seychelles" },
            new() { Id = Guid.NewGuid(), Name = "Sierra Leone" },
            new() { Id = Guid.NewGuid(), Name = "Singapore" },
            new() { Id = Guid.NewGuid(), Name = "Slovakia" },
            new() { Id = Guid.NewGuid(), Name = "Slovenia" },
            new() { Id = Guid.NewGuid(), Name = "Solomon Islands" },
            new() { Id = Guid.NewGuid(), Name = "Somalia" },
            new() { Id = Guid.NewGuid(), Name = "South Africa" },
            new() { Id = Guid.NewGuid(), Name = "Spain" },
            new() { Id = Guid.NewGuid(), Name = "Sri Lanka" },
            new() { Id = Guid.NewGuid(), Name = "Sudan" },
            new() { Id = Guid.NewGuid(), Name = "Sudan, South" },
            new() { Id = Guid.NewGuid(), Name = "Suriname" },
            new() { Id = Guid.NewGuid(), Name = "Sweden" },
            new() { Id = Guid.NewGuid(), Name = "Switzerland" },
            new() { Id = Guid.NewGuid(), Name = "Syria" },
            new() { Id = Guid.NewGuid(), Name = "Taiwan" },
            new() { Id = Guid.NewGuid(), Name = "Tajikistan" },
            new() { Id = Guid.NewGuid(), Name = "Tanzania" },
            new() { Id = Guid.NewGuid(), Name = "Thailand" },
            new() { Id = Guid.NewGuid(), Name = "Togo" },
            new() { Id = Guid.NewGuid(), Name = "Tonga" },
            new() { Id = Guid.NewGuid(), Name = "Trinidad and Tobago" },
            new() { Id = Guid.NewGuid(), Name = "Tunisia" },
            new() { Id = Guid.NewGuid(), Name = "Turkey" },
            new() { Id = Guid.NewGuid(), Name = "Turkmenistan" },
            new() { Id = Guid.NewGuid(), Name = "Tuvalu" },
            new() { Id = Guid.NewGuid(), Name = "Uganda" },
            new() { Id = Guid.NewGuid(), Name = "Ukraine" },
            new() { Id = Guid.NewGuid(), Name = "United Arab Emirates" },
            new() { Id = Guid.NewGuid(), Name = "United Kingdom" },
            new() { Id = Guid.NewGuid(), Name = "United States" },
            new() { Id = Guid.NewGuid(), Name = "Uruguay" },
            new() { Id = Guid.NewGuid(), Name = "Uzbekistan" },
            new() { Id = Guid.NewGuid(), Name = "Vanuatu" },
            new() { Id = Guid.NewGuid(), Name = "Vatican City" },
            new() { Id = Guid.NewGuid(), Name = "Venezuela" },
            new() { Id = Guid.NewGuid(), Name = "Vietnam" },
            new() { Id = Guid.NewGuid(), Name = "Yemen" },
            new() { Id = Guid.NewGuid(), Name = "Zambia" },
            new() { Id = Guid.NewGuid(), Name = "Zimbabwe" }
        };

        foreach (var country in countries)
        {
            modelBuilder.Entity<Country>().HasData(country);
        }

        return countries;
    }
}
